# Docker file used with GitHub actions
# Fetch ubuntu image
FROM ubuntu:24.04

# Install prerequisites
RUN \
  apt update && \
  apt install -y git cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential ninja-build

# Install nano editor, used to edit files inside container
RUN apt-get install -y nano

# Install doxygen and graphviz
RUN apt-get install -y doxygen graphviz

# Install networking utilities
RUN apt-get install -y iputils-ping

## TODO:
# Install dependencies and other required tools (i.e., STM32CubeCLT?)

# Create project directory and set the working directory
RUN \
  pwd \
  && mkdir -p /project/

## TODO:
# Clone any 2nd-party project files to the container
#RUN \
#    cd /project && \
#    git clone https://github.com/SuessLabs/SampleUtilsLibrary.git

# Build project
RUN \
  cd /project && \
  ls -al && \
  cmake --preset Debug && \
  cmake --build --preset app-debug && \
  cmake --preset Release && \
  cmake --build --preset app-release

# Command that will be invoked when the container starts
ENTRYPOINT ["/bin/bash"]
